### ISSUE TITLE
When the piano is played fast, the notes respond slowly

### ISSUE THREAD

**Issue by yk81708090** [WonyJeong/flutter_piano_audio_detection#2]
When the piano is played fast, the notes respond slowly.

Do you have this problem?

How should I optimize my code？

**Comment by WonyJeong** [comment]
Can you tell me about your test environment?
I haven't considered the latency yet.  (iPhone12 has 400ms latency) 
Let's figure out a way together!

**Comment by yk81708090** [comment]
Env: Android 6.1& Android 10 
i think After recording, it need to turn on multi thread， let it can do woker better.

**Comment by yk81708090** [comment]
If multithreading is enabled, the CPU will be sacrificed and the hardware burden will be increased。 ours app use other sdk, it happyed： CPU usage is very high, and GPU drawing cannot keep up and the hardware is very hot。

**Comment by WonyJeong** [comment]
I think the structure that puts a burden on the device is not good. :(
So, I was thinking of applying tflite-gpu-delegate, but it seems to be difficult to confirm the issue of the magenta repository.
🥲
What is the name of the test device?

**Comment by yk81708090** [comment]
Device: RedMi MiUI 11.0.10 、SAMSUNG Galaxy A7

**Comment by WonyJeong** [comment]
I think hardware performance has a lot to do with latency.
We plan to maintain the plugin in the next month.
If you have any good comments, please leave an issue or pr!

Sorry for not being of much help. 😥

**Comment by yk81708090** [comment]
Thanks！ I will let you know if the plug-in has any changes
