### ISSUE TITLE
Some recognization problem

### ISSUE THREAD

**Issue by kevinszjmm** [WonyJeong/flutter_piano_audio_detection#3]
hi,  
   Thank you for sharing such demo, it is perfect
   i am developing a score play app on mobile, i use audio unit to record, but i found sometime, when i play the piano for [4D,6D], it recognized [4D], but not every time, do you have such problem?
And sometime i play more pitches one time, i will miss one or two.

**Comment by WonyJeong** [comment]
In 4D, 6D, 4 and 6 mean an octave? (also, D mean pitch?)

**Comment by kevinszjmm** [comment]
> In 4D, 6D, 4 and 6 mean an octave? (also, D mean pitch?)

YES

**Comment by WonyJeong** [comment]
Sry.
Today, I will test latency and certain notes are not recognized and leave a comment.
