### ISSUE TITLE
Detection not woking correctly

### ISSUE THREAD

**Issue by manoharantechie** [WonyJeong/flutter_piano_audio_detection#4]
If am start the record  its detect continuously. when am not pressing any keys ,its detect something ,Can you fix the issues to detect when i am pressing any key

**Comment by WonyJeong** [comment]
Sorry for the late reply :(

The return value is considered to be the piano key with the closest probability value to white noise.

You could use the following APIs appropriately to distinguish closer piano keys.

``` dart
Map<String, String> getNotesDetail(List<dynamic> event) {
    Map<String, String> result = Map();
    event.forEach((element) {
      result['key'] = getNoteName(element["key"]);
      result['frame'] = element["frame"].toString();
      result['onset'] = element["onset"].toString();
      result['offset'] = element["offset"].toString();
      result['velocity'] = element["velocity"].toString();
    });
    return result;
  }
```
